name = "ForceSpectroscopyMLE"
uuid = "433bd3a4-f2fb-4448-8c1a-c1e8bdb67c8a"
authors = ["Jakob Tómas Bullerjahn <bullerjahn@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
